# Generated by Django 5.0.6 on 2024-07-08 18:18

import django.db.models.deletion
import lista.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCotejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Lista de Cotejo',
                'verbose_name_plural': 'Listas de Cotejos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResolucionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='PuntosListaCotejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_punto', models.IntegerField()),
                ('punto_acta', models.TextField()),
                ('fundamento_legal', models.TextField(blank=True, null=True)),
                ('como_subsanar', models.TextField(blank=True, null=True)),
                ('cumple', models.IntegerField(default=0)),
                ('no_cumple', models.IntegerField(default=1)),
                ('n_a', models.IntegerField(default=2)),
                ('version', models.BooleanField(default=None)),
                ('lista_cotejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.listacotejo')),
            ],
            options={
                'verbose_name': 'Punto de Lista de Cotejo',
                'verbose_name_plural': 'Puntos de Listas de Cotejos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillasBases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=lista.models.upload_to)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lista_cotejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.listacotejo')),
                ('type_resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.resolucionbase')),
            ],
            options={
                'verbose_name': 'Plantilla Base',
                'verbose_name_plural': 'Plantillas Bases',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_version', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('comentario', models.CharField(help_text='Un pequeño comentario para especificar las caracteristicas de la version.', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lista_cotejo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version', to='lista.listacotejo')),
            ],
        ),
    ]
